# Generated by Django 2.1.2 on 2021-01-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_parking_information_user_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parking_information',
            options={'verbose_name': '駐車場情報', 'verbose_name_plural': '駐車場情報'},
        ),
        migrations.AlterModelOptions(
            name='user_information',
            options={'verbose_name': '利用者情報', 'verbose_name_plural': '利用者情報'},
        ),
    ]
